
services:
  postgres:
    image: postgres:16
    container_name: locadora_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: locadora
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: locadora_backend
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 123456
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: locadora_frontend
    depends_on:
      - backend
    environment:
      BACKEND_URL: http://backend:8080
    ports:
      - "3000:3000"

volumes:
  postgres_data:
