spring.application.name=Locadora
spring.datasource.url=jdbc:postgresql://localhost:5432/locadora
spring.datasource.username=locadora_user
spring.datasource.password=locadora123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true